/**
 * Scraping validation constants
 * Contains comprehensive lists for filtering out non-company entities
 */

export const INDUSTRIES = [
  "biotechnology",
  "fintech",
  "edtech",
  "healthtech",
  "proptech",
  "insurtech",
  "agtech",
  "cleantech",
  "ai",
  "machine learning",
  "data analytics",
  "analytics",
  "digital health",
  "hospital & health care",
  "pharmaceuticals",
  "medical device",
  "life sciences",
  "consumer electronics",
  "consumer goods",
  "e-commerce",
  "ecommerce",
  "retail",
  "fashion",
  "apparel",
  "food & beverages",
  "food production",
  "agriculture",
  "farming",
  "real estate",
  "construction",
  "infrastructure",
  "energy",
  "oil & energy",
  "renewables",
  "environment",
  "climate",
  "sustainability",
  "transportation",
  "mobility",
  "autonomous vehicles",
  "aviation",
  "aerospace",
  "defense",
  "manufacturing",
  "industrial",
  "chemicals",
  "materials",
  "semiconductors",
  "hardware",
  "software",
  "saas",
  "enterprise",
  "b2b",
  "b2c",
  "marketplace",
  "platform",
  "network",
  "social",
  "media",
  "entertainment",
  "gaming",
  "video games",
  "music",
  "film",
  "animation",
  "publishing",
  "education",
  "e-learning",
  "finance",
  "banking",
  "payments",
  "insurance",
  "investment",
  "venture capital",
  "private equity",
  "blockchain",
  "crypto",
  "web3",
  "nft",
  "telecommunications",
  "wireless",
  "iot",
  "robotics",
  "drones",
  "space",
  "nanotechnology",
  "quantum",
  "cybersecurity",
  "security",
  "privacy",
  "compliance",
  "legal",
  "hr",
  "recruiting",
  "talent",
  "marketing",
  "advertising",
  "sales",
  "crm",
  "productivity",
  "collaboration",
  "communication",
  "design",
  "creative",
  "photography",
  "hospitality",
  "travel",
  "tourism",
  "non-profit",
  "government",
  "public sector",
  "defense & space",
  "packaging",
  "cosmetics",
  "wine",
  "spirits",
  "tobacco",
  "utilities",
  "public safety",
  "mental health",
  "wellness",
  "fitness",
  "sports",
  "online dating",
  "dating",
  "pets",
  "veterinary",
  "computer vision",
  "fine art",
  "mobile",
  "consumer",
  "govtech",
  "public",
  "logistics",
  "supply chain",
  "maritime",
  "shipping",
  "freight",
  "trade",
  "import",
  "export",
];

export const LOCATIONS = [
  "united states",
  "usa",
  "california",
  "new york",
  "texas",
  "florida",
  "massachusetts",
  "washington",
  "illinois",
  "pennsylvania",
  "ohio",
  "georgia",
  "north carolina",
  "michigan",
  "new jersey",
  "virginia",
  "arizona",
  "tennessee",
  "indiana",
  "missouri",
  "maryland",
  "wisconsin",
  "colorado",
  "minnesota",
  "alabama",
  "louisiana",
  "kentucky",
  "oregon",
  "oklahoma",
  "connecticut",
  "utah",
  "nevada",
  "arkansas",
  "mississippi",
  "kansas",
  "new mexico",
  "nebraska",
  "delaware",
  "san francisco",
  "new york city",
  "los angeles",
  "chicago",
  "boston",
  "seattle",
  "austin",
  "denver",
  "atlanta",
  "miami",
  "dallas",
  "houston",
  "philadelphia",
  "portland",
  "detroit",
  "london",
  "paris",
  "berlin",
  "tokyo",
  "beijing",
  "shanghai",
  "hong kong",
  "singapore",
  "dubai",
  "abu dhabi",
  "mumbai",
  "delhi",
  "bangalore",
  "sydney",
  "melbourne",
  "toronto",
  "vancouver",
  "montreal",
  "china",
  "india",
  "japan",
  "germany",
  "france",
  "united kingdom",
  "canada",
  "australia",
  "brazil",
  "mexico",
  "spain",
  "italy",
  "netherlands",
  "switzerland",
  "sweden",
  "denmark",
  "norway",
  "finland",
  "poland",
  "ireland",
  "israel",
  "south korea",
  "taiwan",
  "thailand",
  "indonesia",
  "malaysia",
  "philippines",
  "vietnam",
  "uae",
  "saudi arabia",
  "egypt",
  "south africa",
  "nigeria",
  "kenya",
  "ghana",
  "argentina",
  "chile",
  "colombia",
  "peru",
  "greece",
  "portugal",
  "austria",
  "belgium",
  "czech republic",
  "hungary",
  "romania",
  "bulgaria",
  "croatia",
  "lithuania",
  "latvia",
  "estonia",
  "sri lanka",
  "bangladesh",
  "pakistan",
  "new zealand",
  "puerto rico",
];

export const NAVIGATION_ELEMENTS = [
  "home",
  "about",
  "account",
  "login",
  "logout",
  "sign in",
  "sign up",
  "register",
  "upgrade",
  "subscribe",
  "privacy policy",
  "terms of use",
  "terms of service",
  "cookie policy",
  "contact us",
  "help",
  "support",
  "faq",
  "feedback",
  "settings",
  "dashboard",
  "profile",
  "reply",
  "comment",
  "share",
  "newest first",
  "oldest first",
  "most popular",
  "sponsor",
  "advertisement",
  "ad",
  "menu",
  "navigation",
  "header",
  "footer",
  "sidebar",
  "search",
  "filter",
  "sort by",
  "view all",
  "show more",
  "load more",
  "next",
  "previous",
  "page",
  "marketplace",
  "database",
  "essential introductions",
  "for curious minds",
  "add your comment",
  "free",
  "you currently have",
  "pro subscription",
  "top picks",
  "bonus",
  "book a slot",
  "book now",
  "get started",
  "firstback",
  "market maps",
  "archive",
  "back",
  "learn more",
  "read more",
  "see more",
  "explore",
  "discover",
  "try for free",
  "start trial",
  "pricing",
  "features",
  "resources",
  "blog",
  "news",
  "events",
  "careers",
  "press",
  "investors",
  "legal",
  "accessibility",
  "sitemap",
  "ai bubble",
  "signals",
  "intensifying",
  "ai bubble signals intensifying",
];

export const DESCRIPTION_STARTERS = [
  "we ",
  "building ",
  "creating ",
  "developing ",
  "providing ",
  "offering ",
  "delivering ",
  "making ",
  "using ",
  "bringing ",
  "helping ",
  "enabling ",
  "transforming ",
  "revolutionizing ",
  "democratizing ",
  "decoding ",
  "automated ",
  "automating ",
  "ai for ",
  "platform for ",
  "tool for ",
  "solution for ",
];

export const FUNDING_STAGES = [
  "seed",
  "series a",
  "series b",
  "series c",
  "series d",
  "series e",
  "pre-seed",
  "ipo",
  "acquired",
];

export const GENERIC_TERMS = [
  "companies",
  "startups",
  "ventures",
  "enterprises",
  "businesses",
  "firms",
  "organizations",
  "welcome to",
  "introducing",
];

export const JOB_PATTERNS = [
  /view \d+ open job/i,
  /interestedview/i,
  /\d+ open position/i,
  /\d+ opening/i,
  /apply now/i,
  /see jobs/i,
];

export const EXCLUDE_PATTERNS = [
  "add us on",
  "follow us on",
  "share on",
  "subscribe",
  "by ",
  "last updated",
  "rating:",
  "score:",
  "posted on",
  "published on",
];

export const MAX_COMPANY_NAME_LENGTH = 60;
export const MIN_COMPANY_NAME_LENGTH = 2;
export const MAX_COMPANY_NAME_WORDS = 6;

export const SCRAPING_CONFIG = {
  maxScrollAttempts: 200,
  maxLoadMoreClicks: 50,
  maxPaginationPages: 10,
  scrollTimeout: 1000,
  buttonClickTimeout: 2000,
  initialLoadTimeout: 3000,
  chunkSize: 100,
  minCompaniesForDirectExtraction: 20,
  minItemsToTriggerPuppeteer: 50,
};
